# تعریف pipeline برای CI/CD در GitHub Actions
name: CI/CD Pipeline

on:
  push:
    branches: [main]  # با هر push روی main اجرا شود

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest  # اجرای job در یک ماشین لینوکسی

    steps:
      # گام اول: دریافت کد پروژه
      - name: Checkout source code
        uses: actions/checkout@v3

      # گام دوم: نصب نسخه پایتون مورد نیاز
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # گام سوم: نصب وابستگی‌ها
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # گام چهارم (اختیاری): اجرای تست‌ها
      - name: Run tests (optional)
        run: echo "No test suite configured yet"

      # گام پنجم: ساخت Docker Image
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/startup-namer:latest .

      # گام ششم: ورود به Docker Hub
      - name: Log in to Docker Hub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      # گام هفتم: ارسال تصویر به Docker Hub
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/startup-namer:latest

      # گام هشتم: نصب kubectl
      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      # گام نهم: پیکربندی kubeconfig برای اتصال به کلاستر
      - name: Set Kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config

      # گام دهم: استقرار اپلیکیشن روی Kubernetes
      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml
