apiVersion: v1
kind: Service
metadata:
  name: startup-service
spec:
  selector:
    app: namer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000  # هدایت ترافیک به پورت اپلیکیشن
  type: LoadBalancer  # فعال‌سازی Load Balancing در محیط کلاد