name: CI/CD to ArvanCloud

on:
  push:
    branches: [main]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. کلون کردن سورس کد
      - name: Checkout source code
        uses: actions/checkout@v3

      # 2. نصب پایتون
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # 3. نصب نیازمندی‌ها
      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      # 4. لاگین به Docker Hub
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # 5. ساخت و Push کردن Docker Image
      - name: Build and push image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/startup-namer:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/startup-namer:latest

      # 6. نصب kubectl برای استقرار در آروان
      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      # 7. قرار دادن kubeconfig از سکرت
      - name: Set Kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config

      # 8. استقرار در کلاستر آروان
      - name: Deploy to Arvan Kubernetes
        run: |
          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml
          kubectl apply -f postgres-deployment.yaml
          kubectl apply -f redis-deployment.yaml